config/routes.rb
Kvartala::Application.routes.draw do

  resources :messages

  devise_for :users
  resources :users, :only => :show
  root :to => "home#index"

  resources :home
  resource :town

  match 'admin' => 'admin/navigations#index'
  
  namespace :admin do
    resources :announcements
    resources :pages
    resources :signs
    resources :languages
    resources :towns do
      resources :districts do
        resources :quarters do
        end
      end
    end
  end

end

app/models/announcement.rb
class Announcement
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :author, :type => String
  field :img_url, :type => String
end

app/models/district.rb
class District
  include Mongoid::Document
  field :name, :type => String

  embedded_in :town, :inverse_of => :district
  embeds_many :quarters
end

app/models/language.rb
class Language
  include Mongoid::Document
  field :name, :type => String
end

app/models/message.rb
class Message
  include Mongoid::Document
  field :name, :type => String
  field :body, :type => String
  field :date, :type => Date
  field :author, :type => String
end

app/models/page.rb
class Page
  include Mongoid::Document
  field :name, :type => String
  field :body, :type => String
  field :published_at, :type => String
  field :author, :type => String
end

app/models/quarter.rb
class Quarter
  include Mongoid::Document
  field :name, :type => String

  embedded_in :district, :inverse_of => :quarter
end

app/models/sign.rb
class Sign
  include Mongoid::Document
  field :name, :type => String
  field :date, :type => String
end

app/models/town.rb
class Town
  include Mongoid::Document
  
  field :name
  field :main_city, :type => Boolean
  
  embeds_many :districts

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
       
  field :name
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation

end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_filter :init_towns

  private
  def init_towns
    @towns = Town.where(:main_city => true).asc(:name).all
  end
end

app/controllers/home_controller.rb
class HomeController < BaseController
  
  def index
    @users = User.all
  end

end

app/controllers/towns_controller.rb
class TownsController < BaseController
  
  def show
    @town = Town.find(params[:id])
    session[:current_town_id]  = @town.id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # http://github.com/fortuity/rails3-mongoid-devise/wiki/Tutorial-%28Walkthrough%29
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/nagvigations_helper.rb
module NagvigationsHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/pages/_form.html.erb
<%= form_for(@admin_page) do |f| %>
  <% if @admin_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_page.errors.count, "error") %> prohibited this admin_page from being saved:</h2>

      <ul>
      <% @admin_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.text_field :published_at %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Редактирай страница</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_page %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<h1>Списък страници</h1>

<table>
  <tr>
    <th>Заглвие</th>
    <th>Текст</th>
    <th>Публикувано на</th>
    <th>Автор</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_pages.each do |admin_page| %>
  <tr>
    <td><%= admin_page.title %></td>
    <td><%= admin_page.body %></td>
    <td><%= admin_page.published_at %></td>
    <td><%= admin_page.author %></td>
    <td><%= link_to 'Show', admin_page %></td>
    <td><%= link_to 'Редактирай', edit_admin_page_path(admin_page) %></td>
    <td><%= link_to 'Изтрий', admin_page, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Нова страница', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<h1>Нова страница</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @admin_page.title %>
</p>

<p>
  <b>Body:</b>
  <%= @admin_page.body %>
</p>

<p>
  <b>Published at:</b>
  <%= @admin_page.published_at %>
</p>

<p>
  <b>Author:</b>
  <%= @admin_page.author %>
</p>


<%= link_to 'Edit', edit_admin_page_path(@admin_page) %> |
<%= link_to 'Back', admin_pages_path %>