config/routes.rb
Kvartala::Application.routes.draw do

  resources :messages

  devise_for :users
  resources :users, :only => :show
  root :to => "home#index"

  resources :home
  resource :town

  match 'admin' => 'admin/navigations#index'
  
  namespace :admin do
    resources :announcements
    resources :pages
    resources :signs
    resources :languages
    resources :towns do
      resources :districts do
        resources :quarters do
        end
      end
    end
  end

end

app/models/admin/page.rb
class Admin::Page
  include Mongoid::Document
  field :title, :type => String
  field :body, :type => String
  field :published_at, :type => String
  field :author, :type => String
end

app/models/announcement.rb
class Announcement
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :author, :type => String
  field :img_url, :type => String
end

app/models/district.rb
class District
  include Mongoid::Document
  field :name, :type => String

  embedded_in :town, :inverse_of => :district
  embeds_many :quarters
end

app/models/language.rb
class Language
  include Mongoid::Document
  field :name, :type => String
end

app/models/message.rb
class Message
  include Mongoid::Document
  field :name, :type => String
  field :body, :type => String
  field :date, :type => Date
  field :author, :type => String
end

app/models/page.rb
class Page
  include Mongoid::Document
  field :name, :type => String
  field :body, :type => String
  field :published_at, :type => String
  field :author, :type => String
end

app/models/quarter.rb
class Quarter
  include Mongoid::Document
  field :name, :type => String

  embedded_in :district, :inverse_of => :quarter
end

app/models/sign.rb
class Sign
  include Mongoid::Document
  field :name, :type => String
  field :date, :type => String
end

app/models/town.rb
class Town
  include Mongoid::Document
  
  field :name
  field :main_city, :type => Boolean
  
  embeds_many :districts

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
       
  field :name
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation

end

app/controllers/admin/towns_controller.rb
class Admin::TownsController < Admin::BaseController
  
  # cancan
  load_resource :town

  # GET /towns
  # GET /towns.xml
  def index

    @search = TownSearch.new(params[:search] || {})
    town = @search.get_wheres
    @towns = town.all.paginate(:page => params[:page], :per_page => 25)
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @towns }
    end
  end

  # GET /towns/1
  # GET /towns/1.xml
  def show
    @town = Town.find(params[:id])

    respond_to do |format|
      format.html #show.html.erb
      format.xml  { render :xml => @town }
    end
  end

  # GET /towns/new
  # GET /towns/new.xml
  def new
    @town = Town.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @town }
    end
  end

  # GET /towns/1/edit
  def edit
    @town = Town.find(params[:id])
  end

  # POST /towns
  # POST /towns.xml
  def create
    @town = Town.new(params[:town])

    respond_to do |format|
      if @town.save
        format.html { redirect_to(edit_admin_town_path(@town), :notice => 'Town was successfully created.') }
        format.xml  { render :xml => @town, :status => :created, :location => @town }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @town.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /towns/1
  # PUT /towns/1.xml
  def update
    @town = Town.find(params[:id])

    respond_to do |format|
      if @town.update_attributes(params[:town])
        format.html { redirect_to(edit_admin_town_path(@town), :notice => 'Town was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @town.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /towns/1
  # DELETE /towns/1.xml
  def destroy

    # @town = Town.find(params[:id])
    @town.destroy

    respond_to do |format|
      format.html { redirect_to [:admin, :towns], :notice => 'Town was successfully deleted.' }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_filter :init_towns

  private
  def init_towns
    @towns = Town.where(:main_city => true).asc(:name).all
  end
end

app/controllers/home_controller.rb
class HomeController < BaseController
  
  def index
    @users = User.all
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  layout "admin"
  # GET /messages
  # GET /messages.xml
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to(@message, :notice => 'Message was successfully created.') }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to(@message, :notice => 'Message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/towns_controller.rb
class TownsController < BaseController
  
  def show
    @town = Town.find(params[:id])
    session[:current_town_id]  = @town.id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # http://github.com/fortuity/rails3-mongoid-devise/wiki/Tutorial-%28Walkthrough%29
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/nagvigations_helper.rb
module NagvigationsHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/towns/_form.html.erb
<%= semantic_form_for([:admin, @town]) do |f| %>
  <% if @town.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@town.errors.count, "error") %> prohibited this town from being saved:</h2>

      <ul>
        <% @town.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% f.inputs :name => "Основна информация"  do %>
    <%= f.input :name %>
    <%= f.input :main_city, :as => :boolean %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/admin/towns/edit.html.erb
<h1>Редактирай <%= @town.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @town] %> |
<%= link_to 'Back', admin_town_path(@town) %>

app/views/admin/towns/index.html.erb
<h1>Списък градове</h1>

<%= form_for :search, @search, :html => {:method => :get} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />
  <%= f.submit "Search"%>
<% end %>


<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @towns.each do |town| %>
    <tr>
      <td><%= link_to town.name, [:admin, town] %></td>
      <td><%= link_to 'Редактирай', edit_admin_town_path(town) %></td>
      <td><%= link_to 'Изтрий', [:admin, town], :confirm => 'Are you sure?', :method => :delete %></td>
      <td><%= link_to 'Райони', admin_town_districts_path(town) %></td>
    </tr>
  <% end %>
</table>
  
<%= will_paginate @towns %>
  
<br />

<%= link_to 'Нов град', new_admin_town_path %>

app/views/admin/towns/new.html.erb
<h1>Нов град</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_towns_path %>

app/views/admin/towns/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Град <%= @town.name %> </h1>
<table>

  <tr>
    <td>Град: <%= @town.name %></td>
  </tr>
  <tr>
    <td>Райони: 
      <% @town.districts.each do |district| %>
        <p><%= district.name %></p>
      <% end %>
    </td>
  </tr>



</table>

<br />

<%= link_to 'Back', admin_towns_path(@admin) %>

app/views/towns/show.html.erb
<% content_for :title do %>
<h1>Избери квартал от <%= @town.name %></h1>
<% end %>

<ul>
  <%
  @town.districts.each do |disctict|
    disctict.quarters.each do |quarter|
    %>
      <%= content_tag :li, link_to(quarter.name, "#") %>
    <%
    end
  end
%>
</ul>