config/routes.rb
Kvartala::Application.routes.draw do

  resources :messages

  devise_for :users
  resources :users, :only => :show
  root :to => "home#index"

  resources :home
  resource :town

  match 'admin' => 'admin/navigations#index'
  
  namespace :admin do
    resources :announcements
    resources :pages
    resources :signs
    resources :languages
    resources :towns do
      resources :districts do
        resources :quarters do
        end
      end
    end
  end

end

app/models/announcement.rb
class Announcement
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :author, :type => String
  field :img_url, :type => String
end

app/models/district.rb
class District
  include Mongoid::Document
  field :name, :type => String

  embedded_in :town, :inverse_of => :district
  embeds_many :quarters
end

app/models/language.rb
class Language
  include Mongoid::Document
  field :name, :type => String
end

app/models/message.rb
class Message
  include Mongoid::Document
  field :name, :type => String
  field :body, :type => String
  field :date, :type => Date
  field :author, :type => String
end

app/models/page.rb
class Page
  include Mongoid::Document
  field :name, :type => String
  field :body, :type => String
  field :published_at, :type => String
  field :author, :type => String
end

app/models/quarter.rb
class Quarter
  include Mongoid::Document
  field :name, :type => String

  embedded_in :district, :inverse_of => :quarter
end

app/models/sign.rb
class Sign
  include Mongoid::Document
  field :name, :type => String
  field :date, :type => String
end

app/models/town.rb
class Town
  include Mongoid::Document
  
  field :name
  field :main_city, :type => Boolean
  
  embeds_many :districts

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
       
  field :name
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation

end

app/controllers/admin/districts_controller.rb
class Admin::DistrictsController < Admin::BaseController
  # cancan
  load_resource :town, :parent => true
  load_resource :district, :through => :town

  # GET /districts
  # GET /districts.xml
  def index
    #    @districts = District.all
    @districts = @town.districts.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @districts }
    end
  end

  # GET /districts/1
  # GET /districts/1.xml
  def show
    #@district = District.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @district }
    end
  end

  # GET /districts/new
  # GET /districts/new.xml
  def new
    @district = District.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @district }
    end
  end

  # GET /districts/1/edit
  def edit
    #    @district = District.find(params[:id])
    # Town.find(id).district.find(123)
  end

  # POST /districts
  # POST /districts.xml
  def create
    #    @district = District.new(params[:district])
    @district = @town.districts.build(params[:district])

    #    raise @district.inpsect

    respond_to do |format|
      if @district.save
        format.html { redirect_to(edit_admin_town_district_path(:town_id => @town.id.to_param, :id => @district.id.to_param), :notice => 'District was successfully created.') }
        format.xml  { render :xml => @district, :status => :created, :location => @district }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @district.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /districts/1
  # PUT /districts/1.xml
  def update
    #    @district = District.find(params[:id])
    @district = @town.districts.find(params[:id])

    respond_to do |format|
      if @district.update_attributes(params[:district])
        format.html { redirect_to(edit_admin_town_district_path(:town_id => @town.id.to_param, :id => @district.id.to_param), :notice => 'District was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @district.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /districts/1
  # DELETE /districts/1.xml
  def destroy
    #@district = District.find(params[:id])
    @district.destroy

    respond_to do |format|
      format.html { redirect_to admin_town_districts_path, :notice => 'Town was successfully deleted.' }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_filter :init_towns

  private
  def init_towns
    @towns = Town.where(:main_city => true).asc(:name).all
  end
end

app/controllers/home_controller.rb
class HomeController < BaseController
  
  def index
    @users = User.all
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  layout "admin"
  # GET /messages
  # GET /messages.xml
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to(@message, :notice => 'Message was successfully created.') }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to(@message, :notice => 'Message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/towns_controller.rb
class TownsController < BaseController
  
  def show
    @town = Town.find(params[:id])
    session[:current_town_id]  = @town.id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # http://github.com/fortuity/rails3-mongoid-devise/wiki/Tutorial-%28Walkthrough%29
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/nagvigations_helper.rb
module NagvigationsHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/districts/_form.html.erb
<%= semantic_form_for([:admin, @town, @district]) do |f| %>
  <% if @district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@district.errors.count, "error") %> prohibited this district from being saved:</h2>

      <ul>
        <% @district.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% f.inputs :name => "Основна информация"  do %>
    <%= f.input :name %>
  <% end %>

  <div class="actions">
    <%= f.buttons %>
  </div>

<% end %>

app/views/admin/districts/edit.html.erb
<h1>Редактирай <%= @district.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @town, @district] %> |
<%= link_to 'Back', admin_town_districts_path(@town) %>

app/views/admin/districts/index.html.erb
<h1>Списък райони <%= @town.name %></h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @districts.each do |district| %>
    <tr>
      <td><%= link_to district.name, admin_town_district_path(:town_id => @town.id.to_param, :id => district.id.to_param) %></td>
      <td><%= link_to 'Редактирай', edit_admin_town_district_path(@town, district) %></td>
      <td><%= link_to 'Изтрий', [:admin, @town, district], :confirm => 'Are you sure?', :method => :delete %></td>
      <td><%= link_to 'Квартали', admin_town_district_quarters_path(@town, district) %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'Нов район', new_admin_town_district_path(@town) %> <br />
<%= link_to 'Обратно', admin_towns_path %>

app/views/admin/districts/new.html.erb
<h1>Нов район</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_town_districts_path(@town) %>

app/views/admin/districts/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Район <%= @district.name %> </h1>

<table>
  <tr>
    <td>Район: <%= @district.name %></td>
  </tr>
  <tr>
    <td>Квартали: <% @district.quarters.each do |quarter| %>
        <p><%= quarter.name %></p>
      <% end %></td>
  </tr>

</table>

<br />


<%= link_to 'Back', admin_town_districts_path(@town) %>